version: '3'
services:
  spark:
    container_name: spark
    depends_on:
      - kafka
    build:
      context: .
    ports:
      - 8080:8080 # Master
      - 8081:8081 # Worker
      - 4040:4040 # Driver
      - 9870:9870 # Hadoop Site
    networks:
      - default_net
  kafka:
    image: spotify/kafka
    container_name: kafka
    networks:
      - default_net
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=youtube
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"
    networks:
      - default_net
networks:
  default_net: